// Copies the browser libraries the web UI uses from node_modules into
// web/vendor, which is committed so building needs only Go. Run it with
// `make vendor` after changing versions in package.json.
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundledLanguages } from '../web/syntax.js';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const modules = join(repo, 'node_modules');
const out = join(repo, 'web', 'vendor');

// Refuse to copy from node_modules unless it holds what the lockfile pins.
const lock = JSON.parse(readFileSync(join(repo, 'package-lock.json'), 'utf8'));
const version = (name) => JSON.parse(readFileSync(join(modules, name, 'package.json'), 'utf8')).version;
for (const name of Object.keys(lock.packages[''].devDependencies)) {
  const want = lock.packages[`node_modules/${name}`].version;
  if (version(name) !== want) {
    throw new Error(`node_modules has ${name} ${version(name)}, the lockfile pins ${want}: run npm ci`);
  }
}

// Copies a file into web/vendor, leaving out source map comments as the maps
// themselves aren't bundled.
function copy(from, to) {
  mkdirSync(dirname(join(out, to)), { recursive: true });
  if (!to.endsWith('.js')) return copyFileSync(join(modules, from), join(out, to));
  const text = readFileSync(join(modules, from), 'utf8');
  writeFileSync(join(out, to), text.replace(/^\/\/# sourceMappingURL=.*\n?/gm, ''));
}

rmSync(out, { recursive: true, force: true });

copy('marked/lib/marked.esm.js', 'marked.esm.js');
copy('marked/LICENSE', 'marked-LICENSE.txt');

const hljs = '@highlightjs/cdn-assets';
copy(`${hljs}/es/core.min.js`, 'highlight/core.min.js');
copy(`${hljs}/LICENSE`, 'highlight/LICENSE.txt');
for (const lang of bundledLanguages) {
  copy(`${hljs}/es/languages/${lang}.min.js`, `highlight/languages/${lang}.min.js`);
}

writeFileSync(join(out, 'README.md'), `# Vendored browser libraries

Generated by \`make vendor\` from the versions in package.json; don't edit
these files by hand.

- marked ${version('marked')}
- highlight.js ${version(hljs)} (${bundledLanguages.length} languages, listed in web/syntax.js)
`);
console.log(`web/vendor: marked ${version('marked')}, highlight.js ${version(hljs)} with ${bundledLanguages.length} languages`);
